[package]
name = "car"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "z"
incremental = false

[features]
default = ["panic-halt"]

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
panic-halt = { version = "0.2.0", optional = true }
tm4c123x-hal = { git = "https://github.com/nhwn/tm4c-hal.git" }
blake2 = { version = "0.10.4", default-features = false }
chacha20poly1305 = { version = "0.10.1", default-features = false }
p256 = {version = "0.10.1", default-features = false, features = ["ecdsa", "sha256"] }
rand_chacha = { version = "0.3.1", default-features = false }
static_assertions = "1.1.0"

